###############################################################################
#                          Generated on dockerConf.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: docker-symfony4-mysql
      working_dir: /application
      volumes:
        - .:/application
        - ./dockerConf/sql/sql.cnf:/etc/mysql/conf.d/custom.cnf
      environment:
        - MYSQL_ROOT_PASSWORD=dbrootpw
        - MYSQL_DATABASE=docker_symfony4
        - MYSQL_USER=dbuser
        - MYSQL_PASSWORD=dbpw
      ports:
        - "3306:3306"
    adminer:
      image: adminer
      ports:
        - "8080:8080"
    flyway:
      image: flyway/flyway
      command: -url=jdbc:mysql://mysql/docker_symfony4 -schemas=docker_symfony4 -user=root -password=dbrootpw -connectRetries=60 migrate
      volumes:
        - .:/flyway/sql
      depends_on:
        - mysql
    webserver:
      image: nginx:alpine
      container_name: docker-symfony4-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./dockerConf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"
    php-fpm:
      build: dockerConf/php-fpm
      container_name: docker-symfony4-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./dockerConf/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    rabbitmq:
      image: rabbitmq:3.7.5-management
      working_dir: /app
      hostname: rabbit-mq
      container_name: 'rabbit-mq'
      volumes:
        - ./dockerConf/rabbitMq/definitions.json:/etc/rabbitmq/definitions.json
        - ./dockerConf/rabbitMq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      ports:
        - '15672:15672'
        - '5672:5672'


